fos_user:
    db_driver: orm
    firewall_name: main
    user_class: UserBundle\Entity\User
    from_email:
        address:        contact@atypikhous.com
        sender_name:    Equipe AtypikHouse
    service:
        mailer: fos_user.mailer.twig_swift
    registration:
        form:
            name: user_registration
