<?php

namespace PaymentBundle\Repository;

/**
 * PaymentInfosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentInfosRepository extends \Doctrine\ORM\EntityRepository
{
}
