<?php

namespace UserBundle\Repository;

/**
 * UserProfessionalInfosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserProfessionalInfosRepository extends \Doctrine\ORM\EntityRepository
{
}
