<?php

namespace UserBundle\Repository;

/**
 * UserWichListValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserWishListValueRepository extends \Doctrine\ORM\EntityRepository
{
}
