<?php

namespace HousingBundle\Repository;

/**
 * HousingDetailTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HousingTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
