<?php

namespace HousingBundle\Repository;

/**
 * HousingDetailValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HousingDetailValueRepository extends \Doctrine\ORM\EntityRepository
{
}
