<?php

namespace HousingBundle\Repository;

/**
 * HousingImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HousingImagesRepository extends \Doctrine\ORM\EntityRepository
{
}
