<?php

namespace UserBundle\Repository;

/**
 * UserWishlistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserWishlistRepository extends \Doctrine\ORM\EntityRepository
{
}
