<?php

namespace UserBundle\Repository;

/**
 * UserPersonalInfosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPersonalInfosRepository extends \Doctrine\ORM\EntityRepository
{
}
