<?php

namespace UserBundle\Repository;

/**
 * UserScoreCardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserScoreCardRepository extends \Doctrine\ORM\EntityRepository
{
}
