<?php

namespace HousingBundle\Repository;

/**
 * HousingDocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HousingDocumentRepository extends \Doctrine\ORM\EntityRepository
{
}
