<?php

namespace HousingBundle\Repository;

/**
 * HousingNotationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HousingNotationRepository extends \Doctrine\ORM\EntityRepository
{
}
