<?php

namespace HousingBundle\Repository;

/**
 * HousingDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HousingDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
