<?php

namespace HousingBundle\Repository;

/**
 * HousingNotationTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HousingNotationTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
